name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb5e789cbed7c8c2300f3889ec93eb94091e16cffeda38572f7cbdd0b942111"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
