name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d89bb877e9832ab85e103a63527bef626b0af035daa2e12286209f8de3f0197"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
