name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28a09b4f7eee640067e20b56c8b2fef9a1596e3a168ca6875b35054942399871"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
