name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f590b251e849af2f1b7bdf9880887efb443ebc7976a18482957506e8cee2d697"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
