name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1536c6e7c60607979195c1b4b8a53e809110f1e3aecb586f6523c0418b8d93fa"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
