name = "Create Stuff"
author = "oskah"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f78139db6c9dab7194bc415c30d10fc47fce192542622a8b63f13b0a2f904ed1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
